apiVersion: v1
kind: Pod
metadata:
  name: my-labeled-pod
  labels:
    app: my-application
    environment: development
    tier: frontend
    region: ind
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
