kind: Pod
apiVersion: v1
metadata:
  name: multicontainer
  annotations:
    description: this is a testpod
spec:
  containers:
    #first container
    - name: container1
      image: ubuntu
      command: ["/bin/bash","-c","while true;do echo first container;sleep 5;done"]

    #second container
    - name: container2
      image: ubuntu
      command: ["/bin/bash","-c","while true;do echo second container;sleep 5;done"]
  restartPolicy: Never
